# -*- coding: utf-8 -*-
"""data_set_spotify.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xA45AFX77cf77_szRg4rjAQikLruQbDH
"""

import streamlit as st
import pandas as pd
st.set_page_config(page_title="MusicStream", layout="wide")
@st.cache_data
def load_data():
    df = pd.read_csv("/content/archive (5).zip.csv")
    df['duration'] = df['duration'].fillna(0)
    df['release_date'] = pd.to_datetime(df['release_date'])
    return df

df = load_data()

st.sidebar.title("🎵 MusicStream")
menu = st.sidebar.radio("Navigation", ["Home", "Library", "Search", "Top Charts"])

if menu == "Home":
    st.title("Welcome back!")
    st.subheader("Recommended for You")
    cols = st.columns(4)
    random_picks = df.sample(4)

    for i, (idx, row) in enumerate(random_picks.iterrows()):
        with cols[i]:
            st.image("https://via.placeholder.com/150", use_column_width=True) # Placeholder for album art
            st.write(f"**{row['song_title']}**")
            st.caption(f"{row['artist']} • {row['genre']}")

elif menu == "Search":
    st.title("Search")
    query = st.text_input("Search by song, artist, or genre")

    if query:
        results = df[
            df['song_title'].str.contains(query, case=False, na=False) |
            df['artist'].str.contains(query, case=False, na=False) |
            df['genre'].str.contains(query, case=False, na=False)
        ]
        st.write(f"Found {len(results)} results:")
        st.dataframe(results[['song_title', 'artist', 'album', 'genre', 'popularity']])

elif menu == "Top Charts":
    st.title("Trending Now")
    top_songs = df.sort_values(by='popularity', ascending=False).head(10)

    # Display top songs in a table with a "Play" button feel
    for idx, row in top_songs.iterrows():
        col1, col2, col3 = st.columns([1, 4, 1])
        with col1:
            st.write(f"#{top_songs.index.get_loc(idx) + 1}")
        with col2:
            st.write(f"**{row['song_title']}** - {row['artist']}")
        with col3:
            if st.button("▶️ Play", key=row['song_id']):
                st.toast(f"Now playing: {row['song_title']}")
st.markdown("---")
player_col1, player_col2, player_col3 = st.columns([1, 2, 1])
with player_col2:
    st.write("⏹️ Previous | ▶️ Play | ⏭️ Next")
    st.progress(40) # Mock progress bar